### ISSUE TITLE
获取token失败，错误消息是 invalid_client, 状态码 400

### ISSUE THREAD

**Issue by chenxizhang** [cnblogs/openapi#18]
![image](https://user-images.githubusercontent.com/1996954/107750954-abfd0400-6d57-11eb-85aa-9c70d9082ae9.png)

**Comment by cnblogs-dudu** [comment]
我这里测试是正常的，请求的 content-type 用的是什么？

**Comment by chenxizhang** [comment]
'content-type': 'application/x-www-form-urlencoded'

**Comment by cnblogs-dudu** [comment]
现在好了，是 ClientCorsOrigins 配置引起的
