### ISSUE TITLE
获取个人博客随笔列表 接口调用返回500

### ISSUE THREAD

**Issue by Bange666** [cnblogs/openapi#32]
请问一下，为什么调用这个接口一直报500： https://api.cnblogs.com/api/blogs/{blogApp}/posts?pageIndex={pageIndex}，
我试了几个其他的接口都没什么问题
![89C5TH0EDKVTYA)N~(55RC8](https://github.com/cnblogs/openapi/assets/51155397/7b7b4d2b-970b-4d39-89b2-73ba1847c88e)

**Comment by cnblogs-team** [comment]
您好，该问题已修复，抱歉，给您带来麻烦了。
