### ISSUE TITLE
refresh_token返回error

### ISSUE THREAD

**Issue by yikolemon** [cnblogs/openapi#33]
refresh_token返回{"error": "invalid_grant"}，请问是博客园关闭了refresh_token吗？
![image](https://github.com/cnblogs/openapi/assets/65761641/a7c576c9-ab68-4c54-8ec5-52aee545c04f)

**Comment by yikolemon** [comment]
非常抱歉，refresh_token工作是正常的：
由于我在获取token时使用的grant_type为client_credentials，获取token返回不包含id_token与refresh_token。更改grant_type为refresh_token一切正常
![image](https://github.com/cnblogs/openapi/assets/65761641/de216997-872f-4c8e-bf46-6b597a81f02b)

**Comment by cnblogs-team** [comment]
您好，如果在 `/connect/authorize` 的请求参数 `scope` 值中增加 `offline_access`，在 `/connect/token` 的请求响应中 refresh token 会与 access token 一起返回，详见 https://q.cnblogs.com/q/143538/
