### ISSUE TITLE
如何获取原始的博文内容

### ISSUE THREAD

**Issue by yikolemon** [cnblogs/openapi#35]
使用open_api文档中的获取博客接口：
https://api.cnblogs.com/api/blogposts/{id}/body
获取到的博文是html格式的内容，如下图，请问如何获取原始格式的博文内容。
![image](https://github.com/cnblogs/openapi/assets/65761641/a6f41c5d-22ca-43eb-9780-8f0bd0862ad5)
查看Issues 23中：https://github.com/cnblogs/openapi/issues/23 的回答，其中需要对 blogPostUrl 进行编码，是如何编码
![image](https://github.com/cnblogs/openapi/assets/65761641/ecaa0d3e-5bdd-44cb-9913-fd89bea2889b)
还请指教，非常感谢。

**Comment by cnblogs-team** [comment]
1. 目前不支持获取 markdown 原始文本，您是需要获取自己博文的原始文本还是其他人的？
2. C#中对应的编码方式是 `Uri.EscapeDataString()`

**Comment by yikolemon** [comment]
@cnblogs-team 已使用博客园metaweblog方式实现了自己的markdown原文获取
